"""nye endringer

Revision ID: 186539ae7ea3
Revises: 
Create Date: 2025-04-27 13:40:25.140797

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '186539ae7ea3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('valgemne')
    # op.drop_table('studyplan_courses')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notification_group_id', sa.String(length=100), nullable=True))
        batch_op.alter_column('program_id', nullable=True)
        batch_op.alter_column('source_program_id', nullable=True)
        batch_op.add_column(sa.Column('sender_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('recipient_id', sa.Integer(), nullable=True))

        batch_op.create_foreign_key(
            'fk_sender_id',  # Unique name for sender_id FK
            'user',  # Referenced table
            ['sender_id'],  # Local column
            ['id']  # Referenced column
        )
        batch_op.create_foreign_key(
            'fk_recipient_id',  # Unique name for recipient_id FK
            'user',  # Referenced table
            ['recipient_id'],  # Local column
            ['id']  # Referenced column
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('studyplan_courses',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('studyplan_id', sa.INTEGER(), nullable=False),
    sa.Column('course_id', sa.INTEGER(), nullable=False),
    sa.Column('semester', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['studyplan_id'], ['studyplan.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('studyplan_id', 'course_id', 'semester', name='unique_semester_course')
    )
    op.create_table('valgemne',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('studyplan_id', sa.INTEGER(), nullable=False),
    sa.Column('course_id', sa.INTEGER(), nullable=False),
    sa.Column('semester', sa.INTEGER(), nullable=False),
    sa.Column('category', sa.VARCHAR(length=20), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['studyplan_id'], ['studyplan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        # Remove the new columns
        batch_op.drop_column('notification_group_id')
        batch_op.drop_column('sender_id')
        batch_op.drop_column('recipient_id')

        # Make program_id and source_program_id non-nullable
        batch_op.alter_column('program_id', nullable=False)
        batch_op.alter_column('source_program_id', nullable=False)

    # ### end Alembic commands ###
