"""Add target_term to Notifications

Revision ID: 9a1ee8dd6ba4
Revises: 186539ae7ea3
Create Date: 2025-04-29 06:09:00.620775

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '9a1ee8dd6ba4'
down_revision = '186539ae7ea3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('target_term', sa.Enum('H', 'V', name='semester_type'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'target_term')

    # ### end Alembic commands ###
